export const FETCH_DATA_PENDING = 'FETCH_DATA_PENDING';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_ERROR = 'FETCH_DATA_ERROR';
export const FILTER_DATA = 'FILTER_DATA';
export const UPDATE_SEARCH_KEY = 'UPDATE_SEARCH_KEY';
